version: '3.8'

services:
  app:
    build: .
    working_dir: /root/app
    container_name: reparaturcafe_app
    environment:
      - DB_MYSQL_HOST=localhost
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_DATABASE=reparaturcafe
      - DB_MYSQL_USER=root
      - DB_MYSQL_PASSWORD=rootpassword
      - NEXT_PUBLIC_API_URL=https://localhost
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1445
    ports:
      - "3000:3000"
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
        - .:/root/app:delegated