version: '3.8'

services:
  app:
    build: .
    container_name: reparaturcafe_app
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_DATABASE=reparaturcafe
      - DB_MYSQL_USER=oskar
      - DB_MYSQL_PASSWORD=randmpassword
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1445
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: reparaturcafe_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=reparaturcafe
      - MYSQL_USER=oskar
      - MYSQL_PASSWORD=randmpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: