[program:reparaturcafe]
command=/home/oskar/reparaturcafe3/.venv/bin/uvicorn --reload --port 8000 --app-dir "/home/oskar/reparaturcafe3/" api.main:app
directory=/home/oskar/reparaturcafe3
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/home/oskar/reparaturcafe3/supervisor_stderr.log
stderr_logfile=/home/oskar/reparaturcafe/supervisor_stderr.log